// Generated by https://quicktype.io

export interface JSONSample {
    toDoList: ToDoList[];
}

export interface ToDoList {
    _id:       string;
    title:     string;
    color:     string;
    time:      string;
    toDoItems: string[];
}


